name: Continuous Integration
on: push
env:
  DB_NAME: test
jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'CREATE DATABASE ${{DB_NAME}};' -uroot -proot
      - name: Checkout repo code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test